/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Ship(props) {
    const { nodes, materials } = useGLTF('assets/ship.gltf');
    return (
        <group {...props} dispose={null}>
            <mesh
                geometry={nodes['Corvette-F3'].geometry}
                material={materials['SF_Corvette_F3.001']}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.001}
            />
        </group>
    );
}

useGLTF.preload('assets/ship.gltf');
